cache: pip

language: python

matrix:
  include:
    - os: windows
      language: bash
      name: Windows
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.7-dev"

install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install python3;
        export PATH=/c/Python37:/c/Python37/Scripts:/c/Python38:/c/Python38/Scripts:$PATH;
        python -m pip install -e .[test];
      else
        pip install -e .[test];
      fi;

script:
    - pytest
